### ISSUE TITLE
Have you compared the generalization ability of vlp-16 data set?

### ISSUE THREAD

**Issue by hunkyu** [BigMoWangying/LiDAR-Iris#1]
Have you compared the generalization ability of vlp-16 dataset?

**Comment by BigMoWangying** [comment]
yes, we hava tested it on our own vlp-16 dataset collected on our campus, more details in our [paper]( https://github.com/BigMoWangying/LiDAR-Iris/blob/master/iros2020.pdf).

**Comment by hunkyu** [comment]
![2020-07-24 16-26-03 的屏幕截图](https://user-images.githubusercontent.com/20533364/88373471-777d2700-cdca-11ea-8147-d927a86b6974.png)
![2020-07-24 16-26-14 的屏幕截图](https://user-images.githubusercontent.com/20533364/88373489-7ea43500-cdca-11ea-9169-2886c133c2bf.png)
./demo ../data/16line.pcd  ../data/16line_2.pcd
I tried the 16-line effect. Does it feel something is wrong?

**Comment by BigMoWangying** [comment]
the pair(16line_1.pcd , 16line_2.pcd) is true loop while 16line.pcd  is not loop with 16line_1.pcd and 16line_2.pcd.

**Comment by BigMoWangying** [comment]
> ![2020-07-24 16-26-03 的屏幕截图](https://user-images.githubusercontent.com/20533364/88373471-777d2700-cdca-11ea-8147-d927a86b6974.png)
> ![2020-07-24 16-26-14 的屏幕截图](https://user-images.githubusercontent.com/20533364/88373489-7ea43500-cdca-11ea-9169-2886c133c2bf.png)
> ./demo ../data/16line.pcd ../data/16line_2.pcd
> I tried the 16-line effect. Does it feel something is wrong?

the pair(16line_1.pcd , 16line_2.pcd) is true loop while 16line.pcd is not loop with 16line_1.pcd and 16line_2.pcd.

**Comment by hunkyu** [comment]
So is it possible that the current method can be looped correctly only if the point clouds of two frames are highly similar

**Comment by BigMoWangying** [comment]
> So is it possible that the current method can be looped correctly only if the point clouds of two frames are highly similar

When the overlap of two point clouds is small, the distance calculated by this method will be large. In real SLAM system, you need to set a threshold to determine whether it is a loop.

**Comment by hunkyu** [comment]
@BigMoWangying I changed the 16 lines and the effect is okay. Where can I output the two-frame RT matrix in the code?
