### ISSUE TITLE
Precision Recall Curve issue

### ISSUE THREAD

**Issue by cattaneod** [BigMoWangying/LiDAR-Iris#3]
First of all, thank you for your work!

I tried to reproduce the precision recall curves reported in your paper (Fig. 10) for the KITTI sequences 00 and 08 using this code.
However, my results are different from the ones reported in the paper:
![image](https://user-images.githubusercontent.com/11426917/99828818-bc884e80-2b5b-11eb-9db9-3d33f9c44217.png)
![image](https://user-images.githubusercontent.com/11426917/99829116-2bfe3e00-2b5c-11eb-807e-a0e8a70899c9.png)

Am I doing something wrong?

**Comment by BigMoWangying** [comment]
Sorry late for reply，the implemented c++ code is a little different with our matlab code used in our paper, and the criteria of our dataset maybe a little different. I am sorry that I can't provide the matlab code.
